print("hello oppaiii")
print("hello oppaiii")
print("hello oppaiii")
print("hello oppaiii")
print("hello oppaiii")
print("hello oppaiii")
print("hello oppaiii")
print("hello oppaiii")
print("hello oppaiii")
print("hello oppaiii")


print('hentai')
print('hentai')
print('hentai')
print('hentai')
print('hentai')
print('hentai')
print('hentai')
print('hentai')